-- vytvoření tabulek
CREATE TABLE ZANR (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nazev VARCHAR(100) NOT NULL,
    popis VARCHAR(4000),
    PRIMARY KEY (id)
);

CREATE TABLE FILM (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nazev VARCHAR(100) NOT NULL,
    stopaz NUMBER(10) NOT NULL CHECK (stopaz >= 0),
    popis VARCHAR(4000),
    zanr_id NUMBER(19) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_film_zanr_idx FOREIGN KEY (zanr_id) REFERENCES ZANR(id)
);

CREATE TABLE MISTO (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nazev VARCHAR(100) NOT NULL,
    kapacita NUMBER(10) CHECK (kapacita >= 0),
    kapacita_personalu NUMBER(10) CHECK (kapacita_personalu >= 0),
    PRIMARY KEY (id)
);

CREATE TABLE PROMITANI (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    od DATE NOT NULL,
    do DATE NOT NULL,
    datum DATE NOT NULL,
    film_id NUMBER(19) NOT NULL,
    misto_id NUMBER(19) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_promitani_film_idx FOREIGN KEY (film_id) REFERENCES FILM(id),
    CONSTRAINT fk_promitani_misto_idx FOREIGN KEY (misto_id) REFERENCES MISTO(id)
);

CREATE TABLE OSOBA (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login VARCHAR(100) UNIQUE NOT NULL,
    heslo VARCHAR(255) NOT NULL,
    email VARCHAR(320) NOT NULL,
    kredit NUMBER(38, 2) DEFAULT 0 NOT NULL,
    soucast_personalu NUMBER(1) DEFAULT 0 NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE VSTUPENKA (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cena NUMBER(38, 2) DEFAULT 0 NOT NULL CHECK (cena >= 0),
    zaplaceno NUMBER(1),
    sedadlo NUMBER(10) CHECK (sedadlo > 0),
    promitani_id NUMBER(19) NOT NULL,
    osoba_id NUMBER(19),
    PRIMARY KEY (id),
    CONSTRAINT fk_vstupenka_promitani_idx FOREIGN KEY (promitani_id) REFERENCES PROMITANI(id),
    CONSTRAINT fk_vstupenka_osoba_idx FOREIGN KEY (osoba_id) REFERENCES OSOBA(id)
);

CREATE TABLE SMENA (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nazev VARCHAR(100) NOT NULL,
    od DATE NOT NULL,
    do DATE NOT NULL,
    bonus NUMBER(38, 2) DEFAULT 0 NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE PRACOVNI_POZICE (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nazev VARCHAR(100) NOT NULL,
    popis VARCHAR(4000),
    funguje NUMBER(1) DEFAULT 0 NOT NULL,
    mzda NUMBER(38, 2) DEFAULT 0 NOT NULL CHECK (mzda >= 0),
    osoba_id NUMBER(19),
    smena_id NUMBER(19) NOT NULL,
    misto_id NUMBER(19),
    PRIMARY KEY (id),
    CONSTRAINT fk_pracovni_pozice_osoba_idx FOREIGN KEY (osoba_id) REFERENCES OSOBA(id),
    CONSTRAINT fk_pracovni_pozice_smena_idx FOREIGN KEY (smena_id) REFERENCES SMENA(id),
    CONSTRAINT fk_pracovni_pozice_misto_idx FOREIGN KEY (misto_id) REFERENCES MISTO(id)
);

CREATE TABLE DNY (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    den VARCHAR(100) NOT NULL,
    bonus NUMBER(38, 2) DEFAULT 0 NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE PRACOVNI_POZICE_A_DNY (
    pracovni_pozice_id NUMBER(19) NOT NULL,
    dny_id NUMBER(19) NOT NULL,
    PRIMARY KEY (pracovni_pozice_id, dny_id),
    CONSTRAINT fk_pracovni_pozice_a_dny_pracovni_pozice_idx FOREIGN KEY (pracovni_pozice_id) REFERENCES PRACOVNI_POZICE(id),
    CONSTRAINT fk_pracovni_pozice_a_dny_dny_idx FOREIGN KEY (dny_id) REFERENCES DNY(id)
);

COMMIT;