-- mazání pohledů
DROP VIEW NAKLADY_NA_TYDEN;
DROP VIEW NAKLADY_NA_TYDEN_JEDNOTLIVE;
DROP VIEW PRACOVNI_POZICE_INFO;
DROP VIEW PROMITANI_INFO;
DROP VIEW SMENA_INFO;
DROP VIEW ZISKY;
DROP VIEW ZISKY_JEDNOTLIVE;

-- mazání cizích klíčů
ALTER TABLE FILM DROP CONSTRAINT fk_film_zanr_idx;
ALTER TABLE PRACOVNI_POZICE DROP CONSTRAINT fk_pracovni_pozice_osoba_idx;
ALTER TABLE PRACOVNI_POZICE DROP CONSTRAINT fk_pracovni_pozice_smena_idx;
ALTER TABLE PRACOVNI_POZICE DROP CONSTRAINT fk_pracovni_pozice_misto_idx;
ALTER TABLE PRACOVNI_POZICE_A_DNY DROP CONSTRAINT fk_pracovni_pozice_a_dny_pracovni_pozice_idx;
ALTER TABLE PRACOVNI_POZICE_A_DNY DROP CONSTRAINT fk_pracovni_pozice_a_dny_dny_idx;
ALTER TABLE PROMITANI DROP CONSTRAINT fk_promitani_film_idx;
ALTER TABLE PROMITANI DROP CONSTRAINT fk_promitani_misto_idx;
ALTER TABLE VSTUPENKA DROP CONSTRAINT fk_vstupenka_promitani_idx;
ALTER TABLE VSTUPENKA DROP CONSTRAINT fk_vstupenka_osoba_idx;

-- mazání tabulek
DROP TABLE DNY;
DROP TABLE FILM;
DROP TABLE MISTO;
DROP TABLE OSOBA;
DROP TABLE PRACOVNI_POZICE;
DROP TABLE PRACOVNI_POZICE_A_DNY;
DROP TABLE PROMITANI;
DROP TABLE SMENA;
DROP TABLE VSTUPENKA;
DROP TABLE ZANR;