-- provedení všech příkazů najdnou
SPOOL b-vse.log

PROMPT (VYDANÉ VSTUPENKY NA 3. PROMÍTÁNÍ)
@b1.sql
PROMPT (VYDÁNÍ NOVÝCH VSTUPENEK NA 3. PROMÍTÁNÍ)
@b2.sql
PROMPT (ZAKOUPENÍ NĚKTERÝCH VSTUPENEK)
@b3.sql
PROMPT (VYDANÉ VSTUPENKY NA 3. PORMÍTÁNÍ OPĚT)
@b4.sql
PROMPT (PŘEHLED DOSAVADNÍCH A PLÁNOVANÝCH ZISKŮ ZA 3. PROMÍTÁNÍ)
@b5.sql

SPOOL OFF

EXIT