-- vydání nových vstupenek
INSERT INTO VSTUPENKA (CENA, ZAPLACENO, SEDADLO, PROMITANI_ID)
VALUES (220, 0, 1, 3);
INSERT INTO VSTUPENKA (CENA, ZAPLACENO, SEDADLO, PROMITANI_ID)
VALUES (220, 0, 2, 3);
INSERT INTO VSTUPENKA (CENA, ZAPLACENO, SEDADLO, PROMITANI_ID)
VALUES (220, 0, 3, 3);
INSERT INTO VSTUPENKA (CENA, ZAPLACENO, SEDADLO, PROMITANI_ID)
VALUES (220, 0, 4, 3);
INSERT INTO VSTUPENKA (CENA, ZAPLACENO, SEDADLO, PROMITANI_ID)
VALUES (220, 0, 5, 3); -- 5

INSERT INTO VSTUPENKA (CENA, ZAPLACENO, SEDADLO, PROMITANI_ID)
VALUES (220, 0, 6, 3);
INSERT INTO VSTUPENKA (CENA, ZAPLACENO, SEDADLO, PROMITANI_ID)
VALUES (220, 0, 7, 3);
INSERT INTO VSTUPENKA (CENA, ZAPLACENO, SEDADLO, PROMITANI_ID)
VALUES (220, 0, 8, 3);
INSERT INTO VSTUPENKA (CENA, ZAPLACENO, SEDADLO, PROMITANI_ID)
VALUES (220, 0, 9, 3);
INSERT INTO VSTUPENKA (CENA, ZAPLACENO, SEDADLO, PROMITANI_ID)
VALUES (220, 0, 10, 3); -- 5

INSERT INTO VSTUPENKA (CENA, ZAPLACENO, SEDADLO, PROMITANI_ID)
VALUES (220, 0, 11, 3);
INSERT INTO VSTUPENKA (CENA, ZAPLACENO, SEDADLO, PROMITANI_ID)
VALUES (220, 0, 12, 3);
INSERT INTO VSTUPENKA (CENA, ZAPLACENO, SEDADLO, PROMITANI_ID)
VALUES (220, 0, 13, 3);
INSERT INTO VSTUPENKA (CENA, ZAPLACENO, SEDADLO, PROMITANI_ID)
VALUES (220, 0, 14, 3);
INSERT INTO VSTUPENKA (CENA, ZAPLACENO, SEDADLO, PROMITANI_ID)
VALUES (220, 0, 15, 3); -- 5

INSERT INTO VSTUPENKA (CENA, ZAPLACENO, SEDADLO, PROMITANI_ID)
VALUES (220, 0, 16, 3);
INSERT INTO VSTUPENKA (CENA, ZAPLACENO, SEDADLO, PROMITANI_ID)
VALUES (220, 0, 17, 3);
INSERT INTO VSTUPENKA (CENA, ZAPLACENO, SEDADLO, PROMITANI_ID)
VALUES (220, 0, 18, 3);
INSERT INTO VSTUPENKA (CENA, ZAPLACENO, SEDADLO, PROMITANI_ID)
VALUES (220, 0, 19, 3);
INSERT INTO VSTUPENKA (CENA, ZAPLACENO, SEDADLO, PROMITANI_ID)
VALUES (220, 0, 20, 3); -- 5

INSERT INTO VSTUPENKA (CENA, ZAPLACENO, SEDADLO, PROMITANI_ID)
VALUES (220, 0, 21, 3);
INSERT INTO VSTUPENKA (CENA, ZAPLACENO, SEDADLO, PROMITANI_ID)
VALUES (220, 0, 22, 3);
INSERT INTO VSTUPENKA (CENA, ZAPLACENO, SEDADLO, PROMITANI_ID)
VALUES (220, 0, 23, 3);
INSERT INTO VSTUPENKA (CENA, ZAPLACENO, SEDADLO, PROMITANI_ID)
VALUES (220, 0, 24, 3);
INSERT INTO VSTUPENKA (CENA, ZAPLACENO, SEDADLO, PROMITANI_ID)
VALUES (220, 0, 25, 3); -- 5

INSERT INTO VSTUPENKA (CENA, ZAPLACENO, SEDADLO, PROMITANI_ID)
VALUES (220, 0, 26, 3);
INSERT INTO VSTUPENKA (CENA, ZAPLACENO, SEDADLO, PROMITANI_ID)
VALUES (220, 0, 27, 3);
INSERT INTO VSTUPENKA (CENA, ZAPLACENO, SEDADLO, PROMITANI_ID)
VALUES (220, 0, 28, 3);
INSERT INTO VSTUPENKA (CENA, ZAPLACENO, SEDADLO, PROMITANI_ID)
VALUES (220, 0, 29, 3);
INSERT INTO VSTUPENKA (CENA, ZAPLACENO, SEDADLO, PROMITANI_ID)
VALUES (220, 0, 30, 3); -- 5

-- 30

COMMIT;