-- některé osoby si koupí vstupenky
UPDATE VSTUPENKA
SET ZAPLACENO = 1,
    OSOBA_ID = 2
WHERE ZAPLACENO = 0
AND PROMITANI_ID = 3
AND OSOBA_ID IS NULL
AND ROWNUM <= 5; -- 5 vstupenek pro osobu id 2

COMMIT;

-- zaplacení
UPDATE OSOBA
SET KREDIT = KREDIT - (
    (SELECT CENA FROM VSTUPENKA WHERE PROMITANI_ID = 3 AND ROWNUM <= 1)*5
)
WHERE ID = 2;

COMMIT;

UPDATE VSTUPENKA
SET ZAPLACENO = 1,
    OSOBA_ID = 10
WHERE ZAPLACENO = 0
AND PROMITANI_ID = 3
AND OSOBA_ID IS NULL
AND ROWNUM <= 1; -- 1 vstupenek pro osobu id 10

COMMIT;

-- zaplacení
UPDATE OSOBA
SET KREDIT = KREDIT - (
    (SELECT CENA FROM VSTUPENKA WHERE PROMITANI_ID = 3 AND ROWNUM <= 1)
)
WHERE ID = 10;

COMMIT;