-- tabulka pro přehled promítání
CREATE OR REPLACE VIEW PROMITANI_INFO AS SELECT f.NAZEV, 
       TO_CHAR(p.DATUM, 'DD. MM. YYYY') AS DATUM,
       m.NAZEV AS MISTO,
       COUNT(v.ZAPLACENO) AS VYDANE_VSTUPENKY,
       COUNT(CASE WHEN v.ZAPLACENO = 1 THEN 1 END) AS PRODANE_VSTUPENKY,
       m.KAPACITA
FROM PROMITANI p
JOIN VSTUPENKA v ON v.PROMITANI_ID = p.ID
JOIN FILM f ON f.ID = p.FILM_ID
JOIN MISTO m ON m.ID = p.MISTO_ID
GROUP BY p.ID, f.NAZEV, p.DATUM, m.NAZEV, m.KAPACITA;