-- tabulka pro přehled zisků
CREATE OR REPLACE VIEW ZISKY_JEDNOTLIVE AS SELECT f.NAZEV, 
       TO_CHAR(p.DATUM, 'DD. MM. YYYY') AS DATUM,
       (AVG(v.CENA) * m.KAPACITA) AS ODHAD_ZA_PROMITANI,
       (AVG(v.CENA) * COUNT(CASE WHEN v.ZAPLACENO = 1 THEN 1 END)) AS ZATIM_ZA_PROMITANI
FROM PROMITANI p
JOIN VSTUPENKA v ON v.PROMITANI_ID = p.ID
JOIN FILM f ON f.ID = p.FILM_ID
JOIN MISTO m ON m.ID = p.MISTO_ID
GROUP BY p.ID, f.NAZEV, p.DATUM, m.KAPACITA;